In [1]:
full_data = r"/pub/data/yangdeq/CLIP/data/vein/25_vein_artery/1.ori_data/imagesTr_ori"
semi_data = r"/pub/data/yangdeq/CLIP/data/vein/25_vein_artery/semi_imagesTr_ori"

In [8]:
import os
import SimpleITK as sitk
full_spacing = []
full_shape = []
for file in os.listdir(full_data):
    img = sitk.ReadImage(os.path.join(full_data, file))
    full_spacing.append(img.GetSpacing()[-1])
    full_shape.append(img.GetSize())
    # print(img.GetSpacing())

In [15]:
max([i[-1] for i in semi_shape])

985

In [9]:
semi_spacing = []
semi_shape = []
for file in os.listdir(semi_data):
    img = sitk.ReadImage(os.path.join(semi_data, file))
    semi_spacing.append(img.GetSpacing()[-1])
    semi_shape.append(img.GetSize())
    # print(img.GetSpacing())

In [1]:
min(full_spacing), max(full_spacing),min(semi_spacing), max(semi_spacing)


NameError: name 'full_spacing' is not defined

In [4]:
path = r"/pub/data/yangdeq/CLIP/data/vein/25_vein_artery/semi_labelsTr_ori"
import os
import SimpleITK as sitk 
import numpy as np
for i in os.listdir(path):
    img = sitk.ReadImage(os.path.join(path, i))
    arr = sitk.GetArrayFromImage(img)
    arr_unique = np.unique(arr)
    print(arr_unique)

[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0